version: '3.1'
services:
  nginx:
    container_name: NGINX       
    build:
      context: .
      dockerfile: nginx_docker
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
